from pathlib import Path


def test_oos_checkpoint_migration_allocates_checkpoint_ids():
    migration = (Path(__file__).parents[1] / "migrations" / "011_resumable_oos_runs.sql").read_text(encoding="utf-8")
    checkpoint_block = migration.split("CREATE TABLE IF NOT EXISTS oos_candidate_checkpoints", 1)[1].split(");", 1)[0]
    assert "checkpoint_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in checkpoint_block
