-- Resumable Final OOS runs (SF-P0-02). Additive and safe for existing rows.
ALTER TABLE oos_authorizations ADD COLUMN IF NOT EXISTS dataset_ref_hash VARCHAR(128) NOT NULL DEFAULT '';
ALTER TABLE oos_authorizations ADD COLUMN IF NOT EXISTS market_snapshot_id VARCHAR(128) NOT NULL DEFAULT '';
ALTER TABLE oos_authorizations ADD COLUMN IF NOT EXISTS content_ref_hash VARCHAR(128);
ALTER TABLE oos_authorizations ADD COLUMN IF NOT EXISTS active_run_id VARCHAR(128);
ALTER TABLE oos_authorizations ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE oos_authorizations ALTER COLUMN status TYPE VARCHAR(32);

CREATE INDEX IF NOT EXISTS ix_oos_authorizations_active_run_id ON oos_authorizations(active_run_id);

CREATE TABLE IF NOT EXISTS oos_evaluation_runs (
    run_id VARCHAR(128) PRIMARY KEY,
    authorization_id VARCHAR(36) NOT NULL REFERENCES oos_authorizations(authorization_id),
    owner_id VARCHAR(128) NOT NULL,
    fencing_token INTEGER NOT NULL DEFAULT 1,
    status VARCHAR(32) NOT NULL DEFAULT 'STARTED',
    lease_expires_at TIMESTAMPTZ NOT NULL,
    evaluator_version VARCHAR(128) NOT NULL DEFAULT 'final-oos-v1',
    cohort_artifact_hash VARCHAR(128),
    sealed_at TIMESTAMPTZ,
    started_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_oos_evaluation_runs_authorization_id ON oos_evaluation_runs(authorization_id);

CREATE TABLE IF NOT EXISTS oos_candidate_checkpoints (
    checkpoint_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id VARCHAR(128) NOT NULL REFERENCES oos_evaluation_runs(run_id),
    candidate_id VARCHAR(128) NOT NULL,
    input_hash VARCHAR(128) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    result JSON,
    result_hash VARCHAR(128),
    error TEXT,
    completed_at TIMESTAMPTZ,
    UNIQUE(run_id, candidate_id)
);
CREATE INDEX IF NOT EXISTS ix_oos_candidate_checkpoints_run_id ON oos_candidate_checkpoints(run_id);

CREATE TABLE IF NOT EXISTS oos_cohort_artifacts (
    artifact_hash VARCHAR(128) PRIMARY KEY,
    run_id VARCHAR(128) NOT NULL UNIQUE REFERENCES oos_evaluation_runs(run_id),
    authorization_id VARCHAR(36) NOT NULL REFERENCES oos_authorizations(authorization_id),
    artifact JSON NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);
